name: figma_dhiwise_ex01
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.0.0
  connectivity_plus: ^4.0.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  equatable: ^2.0.0
  dio: ^5.0.3
  video_player: ^2.7.1
  graphql_flutter: ^5.1.2
dev_dependencies:
  build_runner: ^2.4.5
  flutter_test: 
    sdk: flutter
  graphql_codegen: ^0.13.5
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoItalicThin.ttf
          weight: 100
